### ISSUE TITLE
Problem with BESST in the pipeline

### ISSUE THREAD

**Issue by xbarvazx** [GATB/gatb-minia-pipeline#15]
Hi,

I get the following error at the BESST part of the script, any ideas why?

(2018-05-30 06:24:22) Execution of 'python BESST/runBESST'. Command line: 
     /storage/raz/gatb-minia-pipeline/tools/memused python /storage/raz/gatb-minia-pipeline/BESST/runBESST -c assembly_k121.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000
Number of initial contigs: 54117
Estimating insert size from 1000001 mappings with quality over --min_mapq 11.
Choosing mode: 470
mu_adjusted:562.118735931, sigma_adjusted:191.434136248, skewness_adjusted:0.825079377678
mode adj: 470
median adj 531
Creating contig graph with library:  assembly.lib_0.bam
Traceback (most recent call last):
  File "/storage/raz/gatb-minia-pipeline/BESST/runBESST", line 431, in <module>
    main(args)
  File "/storage/raz/gatb-minia-pipeline/BESST/runBESST", line 182, in main
    (G, G_prime) = CG.PE(Contigs, Scaffolds, Information, C_dict, param, small_contigs, small_scaffolds, bam_file)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/storage/raz/gatb-minia-pipeline/BESST/BESST/CreateGraph.py", line 202, in PE
    CreateEdge(cont_obj1, cont_obj2, scaf_obj1, scaf_obj2, G_prime, param, alignedread, counter, contig1, contig2, save_obs=False)
  File "/storage/raz/gatb-minia-pipeline/BESST/BESST/CreateGraph.py", line 844, in CreateEdge
    G.edge[(scaf_obj1.name, scaf_side1)][(scaf_obj2.name, scaf_side2)]['obs_sq'] = (obs1 + obs2) ** 2
AttributeError: 'Graph' object has no attribute 'edge'
maximal memory used: 285 MB
(2018-05-30 06:24:40) Execution of 'python BESST/runBESST' failed. Command line: 
     /storage/raz/gatb-minia-pipeline/tools/memused python /storage/raz/gatb-minia-pipeline/BESST/runBESST -c assembly_k121.contigs.fa -f assembly.lib_0.bam -o assembly_besst -orientation fr --iter 10000

Thanks,

**Comment by rchikhi** [comment]
Hmm on top of my head, not really, but @ksahlin might know!

**Comment by ksahlin** [comment]
Probably you have networkx >=2.0 installed, see https://github.com/ksahlin/BESST/issues/64 . Installing a lower version of networkx should fix this, e.g., with `pip install 'networkx==1.9' --force-reinstall`.

**Comment by xbarvazx** [comment]
Thanks,
I will try that.
I also changed the hardcode to sspace and it work.

Cheers,

**Comment by rchikhi** [comment]
Thanks Kristoffer!

**Comment by Shirley-Q** [comment]
I also have this error, but I didn't solve it according to your tips(pip install 'networkx==1.9' --force-reinstall).
And I can't understand "changed the hardcode to sspace and it work."
Could you help me?
Best wishes,
Shirley

**Comment by rchikhi** [comment]
The last part refers to changing line https://github.com/GATB/gatb-minia-pipeline/blob/master/gatb#L64 manually.
With BESST, do you get the exact same error message as above after installing networkx 1.9?

**Comment by ksahlin** [comment]
If you get the exact same error after running `pip install 'networkx==1.9' --force-reinstall` it is likely that the pipeline still are using a networkx version >=2.0, maybe from another python installation.

**Comment by mkweskin** [comment]
I was having this problem and saw the networkx <2.0 recommendation in this thread and an issue on [the BESST github Issues list](https://github.com/ksahlin/BESST/issues/68).

Could the gatb-minia-pipeline Readme.md install instructions be updated to include `networkx==1.9`? 😸

**Comment by Krannich479** [comment]
I am running scaffolding successfully with **networkx 1.6**.
See time stamp for reference.

**Comment by rchikhi** [comment]
Readme has been updated to install BESST directly, without installing any prerequisites manually

**Comment by silviajusti** [comment]
I've been getting this error for 3 out of 14 similar samples. All running at the same time, on the same server, under the same conditions...

**Comment by rchikhi** [comment]
for the failing samples, can you try uninstalling besst and networkx and reinstall them through `python2 -m pip install --user BESST`?
